export const BORROW_ACTION_TYPES = {
    ADD_BORROW_START: 'borrow/ADD_BORROW_START',
    FETCH_BORROW_START: 'borrow/FETCH_BORROW_START',
    FETCH_BORROW_SUCCESS: 'borrow/FETCH_BORROW_SUCCESS',
    FETCH_BORROW_FAILED: 'borrow/FETCH_BORROW_FAILED'
};