export const BOOKS_ACTION_TYPES = {
    FETCH_BOOKS_START: 'books/FETCH_BOOKS_START',
    FETCH_BOOKS_SUCCESS: 'books/FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILED: 'books/FETCH_BOOKS_FAILED',
    
    FETCH_BOOKS_PAGE_START: 'books/FETCH_BOOKS_PAGE_START',
    FETCH_BOOKS_PAGE_SUCCESS: 'books/FETCH_BOOKS_PAGE_SUCCESS',
    SET_ERROR: 'books/SET_ERROR',

    INSERT_BOOKS_START: 'books/INSERT_BOOKS_START',
    INSERT_BOOKS_SUCCESS: 'books/INSERT_BOOKS_SUCCESS',
    INSERT_BOOKS_FAILED: 'books/INSERT_BOOKS_FAILED',
};